add dependency to avoid race condition
google/exposure-notifications-private-analytics-ingestion pull request #12
Opened 2021-05-06 17:20 UTC by hostirosti

2021-05-07 22:04 UTC, justinowusu approved these changes, later dismissed
LGTM

2021-05-07 22:07 UTC, bleything requested changes
lgtm aside from one  comment

2021-05-07 22:07 UTC, bleything commented on terraform/iam.tf
> +  depends_on = [google_project_iam_custom_role.terraform_service_account_role]
this should not be necessary. The `role = ` assignment already refers to this resource so the hint already exists.

2021-05-11 17:53 UTC, gurayAlsac approved these changes

2021-05-11 17:53 UTC, justinowusu approved these changes

2021-05-11 18:37 UTC, merged