Update firestore.rules
google/exposure-notifications-private-analytics-ingestion pull request #16
Opened 2021-10-18 14:32 UTC by acq

Biweekly metrics are having their epsilon values changed from 10.2 to 8.
To avoid metrics with different epsilons ending in the same bucket, we decided to have metrics with an epsilon of 8 will appear as -v2.

2021-10-20 16:56 UTC, justinowusu submitted a review, later dismissed
LGTM

2021-10-20 17:22 UTC, gurayAlsac submitted a review, later dismissed

2021-10-20 17:22 UTC, gurayAlsac commented on config/firebase/firestore.rules
> -          'CodeVerifiedWithReportType14d-v1',
Just to make sure, the client doesn't do any sort of retrying if it fails a metric upload, right? Or are there no older devices out in the wild that may continue uploading these metrics?

2021-10-20 17:31 UTC, hostirosti commented on config/firebase/firestore.rules
> -          'CodeVerifiedWithReportType14d-v1',
+1 we might want to consider doing add only and the delete at a later point.

2021-10-20 17:31 UTC, hostirosti commented
/gcbrun

2021-10-20 17:32 UTC, acq commented on config/firebase/firestore.rules
> -          'CodeVerifiedWithReportType14d-v1',
We don't do retries ourselves, but this would happen inside of Firestore.
We have disabled persistence on the client, so it shouldn't keep track of previous uploads (AFAICT).

That being said, if there's any doubt, I don't mind leaving the v1 metrics in the allowlist.
WDYT?

2021-10-20 18:18 UTC, hostirosti requested changes

2021-10-20 18:18 UTC, hostirosti commented on config/firebase/firestore.rules
> -          'CodeVerifiedWithReportType14d-v1',
I'd prefer we leave v1 around for now, no harm and less risk. We can remove them in a later PR.

2021-10-20 22:02 UTC, acq commented on config/firebase/firestore.rules
> -          'CodeVerifiedWithReportType14d-v1',
Sounds good
I've reverted the deletions, so now only v2s are added

2021-11-01 17:03 UTC, hostirosti submitted a review, later dismissed

2021-11-01 17:04 UTC, hostirosti commented
/gcbrun

2021-11-01 17:05 UTC, gurayAlsac submitted a review, later dismissed

2021-11-01 17:54 UTC, gurayAlsac approved these changes

2021-11-01 17:55 UTC, acq commented
/gcbrun

2021-11-01 17:58 UTC, hostirosti commented
/gcbrun

2021-11-01 20:02 UTC, hostirosti approved these changes

2021-11-01 20:02 UTC, merged